// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC63pVZmkuNQzIzaT3jhCFaCX_5QQD-c8o',
    appId: '1:1086161823779:android:9b763aaee61d84fb386996',
    messagingSenderId: '1086161823779',
    projectId: 'cat-cat-5f7eb',
    storageBucket: 'cat-cat-5f7eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_FrwkRjTQdAbxgkS_uN1rNYvMJXfTfT4',
    appId: '1:1086161823779:ios:c336a04f4676756a386996',
    messagingSenderId: '1086161823779',
    projectId: 'cat-cat-5f7eb',
    storageBucket: 'cat-cat-5f7eb.firebasestorage.app',
    androidClientId: '1086161823779-i1t5blqu9mti3spbmarap2nmaj91u2lj.apps.googleusercontent.com',
    iosClientId: '1086161823779-1dhb29ghu5i1p6gu3t8mp1kvr2322m6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.catCat',
  );

}